const T={domains:"Domaine",teamRef:"TEAM_REF",axes:"Axes_Strategiques",objectives:"Objectifs",offers:"Offres_Services",activityOffers:"Activites_OFS",activities:"Activites",team:"Team",projectStages:"Etapes_Projet",featureStages:"Stades_Fonctionnalite",features:"Fonctionnalites",projects:"Projects",tasks:"Tasks",allocations:"Allocations",contrib:"CONTRIBUTIONS_OBJECTIFS",audit:"JOURNAL_ACTIONS"};let db={},search="";const $=x=>document.getElementById(x);function rows(d){if(!d||!Array.isArray(d.id))return[];let k=Object.keys(d);return d.id.map((_,i)=>Object.fromEntries(k.map(x=>[x,Array.isArray(d[x])?d[x][i]:d[x]])))}async function ft(k,t){
  const names=k==="teamRef"?["TEAM_REF","Team_ref"]:[t];
  for(const name of names){
    try{return rows(await grist.docApi.fetchTable(name))}
    catch(e){console.warn(name,e)}
  }
  return[]
}function id(v){if(Array.isArray(v))return v.find(x=>Number.isInteger(x))??null;let n=Number(v);return Number.isFinite(n)?n:null}function refs(v){return Array.isArray(v)?v.filter(Number.isInteger):Number.isInteger(v)?[v]:[]}function get(k,i){return(db[k]||[]).find(r=>r.id==i)||null}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function pct(v){let n=Number(v||0);if(n<=1)n*=100;return Math.round(n)}function dms(v){if(!v)return null;if(typeof v==='number')return v>1e12?v:v*1000;let n=Date.parse(v);return isNaN(n)?null:n}function dt(v){let m=dms(v);return m?new Date(m).toLocaleString('fr-FR'):''}function din(v){let m=dms(v);return m?new Date(m).toISOString().slice(0,10):''}function gd(v){return v?Math.floor(Date.parse(v+'T00:00:00Z')/1000):null}function msg(t){$('banner').textContent=t;$('banner').classList.remove('hidden');setTimeout(()=>$('banner').classList.add('hidden'),2500)}async function apply(a,m){try{await grist.docApi.applyUserActions(a);await load();msg(m)}catch(e){console.error(e);msg('Erreur Grist : '+(e.message||e))}}
const A={
domains:{l:'Domaines',t:'Domaine',k:'domains',f:[['Code','Code','text'],['Nom','Nom','text'],['Description','Description','text']]},
teamRef:{l:'Équipes / TEAM_REF',t:'TEAM_REF',k:'teamRef',f:[['Code','Code','text'],['Libelle','Libellé','text'],['Description','Description','text'],['Domaine_code','Domaine','ref:domains']]},
axes:{l:'Axes stratégiques',t:'Axes_Strategiques',k:'axes',f:[['Code','Code','text'],['Nom','Nom','text'],['Description','Description','text'],['Sponsor','Sponsor','text'],['Priorite','Priorité','text'],['Horizon','Horizon','text'],['Statut','Statut','text']]},objectives:{l:'Objectifs',t:'Objectifs',k:'objectives',f:[['Code','Code','text'],['Nom','Nom','text'],['Axe_Code','Axe','ref:axes'],['KPI','KPI','text'],['Valeur_Cible','Valeur cible','text'],['Echeance','Échéance','date'],['Responsable','Responsable','text'],['Statut','Statut','text'],['Progression','Progression %','percent']]},offers:{l:'Offres de services',t:'Offres_Services',k:'offers',f:[['Code','Code','text'],['Nom','Nom','text'],['Description','Description','text'],['Responsable','Responsable','text'],['Statut','Statut','text']]},activityOffers:{l:'Activités OFS',t:'Activites_OFS',k:'activityOffers',f:[['Activites_Nom','Nom','text'],['OFS_Code','Offre','ref:offers']]},activities:{l:'Activités',t:'Activites',k:'activities',f:[['Code','Code','text'],['Nom','Nom','text'],['Service_Code','Activité OFS','ref:activityOffers'],['Description','Description','text'],['Responsable','Responsable','text'],['Type','Type','text'],['Capacite_ETP','Capacité ETP','number'],['Statut','Statut','text']]},team:{l:'Équipe / Team',t:'Team',k:'team',f:[['nom','Nom','text'],['role','Rôle','text'],['capacite_ETP','Capacité ETP','number']]},projectStages:{l:'Étapes projet',t:'Etapes_Projet',k:'projectStages',f:[['Code','Code','text'],['Nom','Nom','text'],['Ordre','Ordre','number'],['Actif','Actif','bool']]},featureStages:{l:'Stades fonctionnalité',t:'Stades_Fonctionnalite',k:'featureStages',f:[['Code','Code','text'],['Nom','Nom','text'],['Ordre','Ordre','number'],['Actif','Actif','bool']]},features:{l:'Fonctionnalités',t:'Fonctionnalites',k:'features',f:[['Code','Code','text'],['Nom','Nom','text'],['Description','Description','text'],['produit','Produit','ref:projects'],['stade','Stade','ref:featureStages'],['Priorite','Priorité','text'],['Progression','Progression %','percent'],['Date_Cible','Date cible','date'],['Responsable','Responsable','ref:team'],['Actif','Actif','bool']]}};
function deps(k,r){
if(k==='domains')return db.teamRef.filter(x=>id(x.Domaine_code)==r).length;
if(k==='teamRef')return 0;
if(k==='axes')return db.objectives.filter(x=>id(x.Axe_Code)==r).length;if(k==='objectives')return db.contrib.filter(x=>(id(x.Objectif_Libelle)||id(x.Objectif_Code2))==r).length;if(k==='offers')return db.activityOffers.filter(x=>id(x.OFS_Code)==r).length;if(k==='activityOffers')return db.activities.filter(x=>id(x.Service_Code)==r).length;if(k==='activities')return db.projects.filter(x=>id(x.activite)==r).length;if(k==='team')return db.projects.filter(x=>id(x.responsable)==r).length+db.tasks.filter(x=>refs(x.assignees).includes(r)).length+db.allocations.filter(x=>id(x.Ressource_Code)==r).length+db.features.filter(x=>id(x.Responsable)==r).length;if(k==='projectStages')return db.projects.filter(x=>id(x.etape_courante)==r).length+db.tasks.filter(x=>id(x.etape_projet)==r).length;if(k==='featureStages')return db.features.filter(x=>id(x.stade)==r).length;if(k==='features')return db.tasks.filter(x=>id(x.fonctionnalite)==r).length;return 0}function display(r,f){let[n,,t]=f,v=r[n];if(t==='date')return dt(v);if(t==='percent')return pct(v)+'%';if(t==='bool')return v?'Oui':'Non';if(t.startsWith('ref:')){let x=get(t.split(':')[1],id(v));return x?.Nom||x?.nom||x?.Activites_Nom||x?.Code||''}return v??''}
function init(){refSelect.innerHTML=Object.entries(A).map(([k,c])=>`<option value="${k}">${c.l}</option>`).join('')}function renderRefs(){let k=refSelect.value||Object.keys(A)[0],c=A[k],rs=db[c.k]||[];refTable.innerHTML=rs.length?`<table><thead><tr>${c.f.slice(0,6).map(x=>`<th>${x[1]}</th>`).join('')}<th>Usages</th><th></th></tr></thead><tbody>${rs.map(r=>`<tr>${c.f.slice(0,6).map(f=>`<td>${esc(display(r,f))}</td>`).join('')}<td>${deps(k,r.id)}</td><td class="row-actions"><button data-e="${r.id}">Modifier</button><button class="danger" data-d="${r.id}">Supprimer</button></td></tr>`).join('')}</tbody></table>`:'Aucun enregistrement.';document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>openEdit(+b.dataset.e));document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>del(+b.dataset.d))}function field(n,l,t,v){if(t.startsWith('ref:')){let rs=db[t.split(':')[1]]||[];return`<label>${l}<select name="${n}"><option value="">—</option>${rs.map(r=>`<option value="${r.id}" ${id(v)==r.id?'selected':''}>${esc(r.Nom||r.nom||r.Activites_Nom||r.Code||'#'+r.id)}</option>`).join('')}</select></label>`}if(t==='date')return`<label>${l}<input type="date" name="${n}" value="${din(v)}"></label>`;if(t==='number')return`<label>${l}<input type="number" step=".01" name="${n}" value="${v??''}"></label>`;if(t==='percent')return`<label>${l}<input type="number" min="0" max="100" name="${n}" value="${pct(v)}"></label>`;if(t==='bool')return`<label>${l}<select name="${n}"><option value="true" ${v!==false?'selected':''}>Oui</option><option value="false" ${v===false?'selected':''}>Non</option></select></label>`;return`<label>${l}<input name="${n}" value="${esc(v??'')}"></label>`}function openEdit(rid){let k=refSelect.value,c=A[k],r=rid?get(c.k,rid):null;editForm.id.value=rid||'';editTitle.textContent=(rid?'Modifier ':'Créer ')+c.l;editFields.innerHTML=c.f.map(f=>field(f[0],f[1],f[2],r?.[f[0]])).join('');depHint.textContent=rid?deps(k,rid)+' dépendance(s).':'Nouvel enregistrement.';editDialog.showModal()}editForm.onsubmit=async e=>{e.preventDefault();let k=refSelect.value,c=A[k],f=e.currentTarget,rid=+f.id.value||null,o={};for(let[n,,t]of c.f){let el=f.elements[n];o[n]=t.startsWith('ref:')?(el.value?+el.value:null):t==='date'?gd(el.value):t==='number'?(el.value===''?null:+el.value):t==='percent'?(+el.value/100):t==='bool'?(el.value==='true'):el.value}editDialog.close();await apply([[rid?'UpdateRecord':'AddRecord',c.t,rid||null,o]],rid?'Mis à jour.':'Créé.')};async function del(r){let k=refSelect.value,c=A[k],n=deps(k,r);if(n)return msg('Suppression bloquée : '+n+' dépendance(s).');if(confirm('Supprimer définitivement ?'))await apply([['RemoveRecord',c.t,r]],'Supprimé.')}
function renderAudit(){let rs=(db.audit||[]).filter(r=>!search||Object.values(r).some(v=>String(v??'').toLowerCase().includes(search)));let cr=rs.filter(r=>/create|add|cré/i.test(r.Action||'')).length,up=rs.filter(r=>/update|modif/i.test(r.Action||'')).length,de=rs.filter(r=>/delete|suppr/i.test(r.Action||'')).length;auditStats.innerHTML=`<div class="kpi"><b>${rs.length}</b><small>Actions</small></div><div class="kpi"><b>${cr}</b><small>Créations</small></div><div class="kpi"><b>${up}</b><small>Modifications</small></div><div class="kpi"><b>${de}</b><small>Suppressions</small></div>`;if(!db.audit.length)return auditTable.innerHTML='<p>JOURNAL_ACTIONS absente ou vide. Le widget est prêt à la restituer.</p>';auditTable.innerHTML=`<table><thead><tr><th>Date</th><th>Utilisateur</th><th>Origine</th><th>Action</th><th>Table</th><th>Record</th><th>Libellé</th><th>Détails</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(dt(r.Date_Heure))}</td><td>${esc(r.Utilisateur)}</td><td>${esc(r.Origine)}</td><td>${esc(r.Action)}</td><td>${esc(r.Table)}</td><td>${esc(r.Record_ID)}</td><td>${esc(r.Libelle)}</td><td>${esc(r.Details)}</td></tr>`).join('')}</tbody></table>`}function diag(){
diagnostic.textContent=Object.entries(T).map(([k,t])=>{
  const label=k==="teamRef"?"TEAM_REF / Team_ref":t;
  return label.padEnd(28)+(db[k]||[]).length+' ligne(s)'
}).join('\n')
}async function load(){db=Object.fromEntries(await Promise.all(Object.entries(T).map(async([k,t])=>[k,await ft(k,t)])));renderRefs();renderAudit();diag()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['refs','audit','diag','mcd'].forEach(k=>$(k+'View').classList.toggle('hidden',k!==b.dataset.tab))});refSelect.onchange=renderRefs;newRefBtn.onclick=()=>openEdit();auditSearch.oninput=e=>{search=e.target.value.toLowerCase();renderAudit()};refreshAuditBtn.onclick=refreshDiagBtn.onclick=load;closeDialog.onclick=cancelDialog.onclick=()=>editDialog.close();mcdFile.onchange=e=>{let f=e.target.files?.[0];if(!f)return;mcdImage.src=URL.createObjectURL(f);mcdHint.textContent='Prévisualisation locale : '+f.name+'. Pour la partager, remplace mcd.png dans GitHub Pages.'};init();grist.ready({requiredAccess:'full'});grist.onOptions(()=>load());load();